version: "3.7"
services:
  web:
    image: nginx
    volumes:
      - ./ssl:/tmp/ssl
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment: 
      - FLASK_SERVER_ADDR=backend:9091  
    command: /bin/bash -c "envsubst '$$NGINX_HOST $$FLASK_SERVER_ADDR $$NGINX_PORT' < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
  backend:
    build: flask
    environment: 
      - FLASK_SERVER_PORT=9091
    volumes:
      - ./flask:/src
    depends_on:
      -  mongo  
  mongo:
    image: mongo
  bind9:
    restart: always
    image: labbsr0x/dns-bind9
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    volumes:
    - ./bind9:/data # Change volume path